language: node_js
node_js:
- '0.12'
matrix:
  fast_finish: true
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g grunt-cli
script:
- grunt build
deploy:
  provider: npm
  email: simon@simonemms.com
  skip_cleanup: true
  api_key:
    secure: WTcy33WQjQS+7GmQLPWiQZKlTMbEfnUmug79LeOvYTqymiZAlxZqtN8w+uBiAJb49O0WxNWJPWHFsOIhTY0o+uRZguTPE2V21P5eF8/a8IVskJtfGanj/olIZlpERo3rfKZ9HsvfdSBKbHfS1xUiUxFaNzWi2a8z0d1gFGqp+rdXFMy5owKsCkuI2KVJiI91tL1mJndw1I5IoxzN6L6hgD+Q0iLdGzG6ExQx4PXqUmP/jxlM9PokeQd1LE09qyiX8M069V50gUrMRbUQIYspKgQajdqpa13JWOh9U537EbFbGnKIT9aqy56IFzsQHyz0HPUAaCcvNDQe/Zkih7pwEkCf/n1RdIUEad49m9hR+bhZJPgQ6FwJjH9T+l8wqMW5v0YjKpV2Too5baoC+mJcE5mhKIvUXdRt4cK2vj5AjlXZKB85Kr1AzpW9Z0PX9QV3cJ1eHb4DKkTJtBMZwO8ocdHz0cPYBVRn7oar69vBVcYavyNdV0kJNqh4Xo6lN2/uvcqhVGHIzGU9w17DzQMKxRXatNbhwAaQ2EY7bY5XRCQy3vyEXreMeTfERotpyVwmoia4/ym4obzbfXR1ped8nUxSPvTiEMXLTc5lpCy8i5L/A9HoUqp6EgnVNHuGfsZwACaAEhipQfRf/C/Fa6YqrBRQtBUbINqpZJISVjVDx64=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/ng-blueprint
